const users = [
  {
    id: 1,
    name: 'yash lol',
    username: 'ylol',
    email: 'ylol@lol.com',
    token: [],
    passoword: 'admin@123',
  },
  {
    id: 2,
    name: 'yash bhat',
    username: 'bhat',
    email: 'yb@lol.com',
    token: [],
    passoword: 'admin@123',
  },
  {
    id: 3,
    name: 'Clementine Bauch',
    username: 'Samantha',
    email: 'Nathan@yesenia.net',
    token: [],
    passoword: '0lelplR',
  },
  {
    id: 4,
    name: 'Patricia Lebsack',
    username: 'Karianne',
    email: 'Julianne.OConner@kory.org',
    token: [],
    passoword: '0lelplR',
  },
  {
    id: 5,
    name: 'Chelsey Dietrich',
    username: 'Kamren',
    email: 'Lucio_Hettinger@annie.ca',
    token: [],
    passoword: '0lelplR',
  },
  {
    id: 6,
    name: 'Mrs. Dennis Schulist',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
    token: [],
    passoword: '0lelplR',
  },
  {
    id: 7,
    name: 'Kurtis Weissnat',
    username: 'Elwyn.Skiles',
    email: 'Telly.Hoeger@billy.biz',
    token: [],
    passoword: '0lelplR',
  },
  {
    id: 8,
    name: 'Nicholas Runolfsdottir V',
    username: 'Maxime_Nienow',
    email: 'Sherwood@rosamond.me',
    token: [],
    passoword: '0lelplR',
  },
  {
    id: 9,
    name: 'Glenna Reichert',
    username: 'Delphine',
    email: 'Chaim_McDermott@dana.io',
    token: [],
    passoword: '0lelplR',
  },
  {
    id: 10,
    name: 'Clementina DuBuque',
    username: 'Moriah.Stanton',
    email: 'Rey.Padberg@karina.biz',
    token: [],
    passoword: '0lelplR',
  },
];

export { users };
